### ISSUE TITLE
Preserve white-space

### ISSUE THREAD

**Issue by thernstig** [wessberg/cjstoesm#15] opened 2021-05-04 19:32 UTC
I noticed that a every extra new-line (that we have for white-space as readability) in files was removed by the tool. Other than that it worked flawlessly!

This makes it impossible to use the tool, as line-breaks as white-space is important e.g. between functions so it does not become a big blob of text.

**Comment by thernstig** [comment] 2021-05-04 19:33
In addition it removed comments, such as:

```
    log4js.addLayout('json', () => (logEvent) => {
      const generalFields = {
        // Mandatory fields
        foo: '1.0', // Current version of foo
```

The `Current version of foo` was removed by the tool.

**Comment by wessberg** [comment] 2021-05-04 20:35
Hi there,

`cjstoesm` leverages TypeScript to parse your source code into Abstract Syntax Trees grouped together as _Source Files_ in a _Program_, and as with many other ASTs, TypeScript doesn't treat whitespace as nodes in the tree, but rather has its own opinionated printer that doesn't know about or care about the original structure of the source code. So by design, it is not possible to guarantee the same structure as the original code in terms of whitespace. I would generally recommend using a tool such as Prettier in a way that ensures that your code is auto-formatted according to a set of rules you define internally in your team for each commit.

Unfortunately, the same can be said about comments, but this should be fixable. So I'll close this issue and create another one for tracking the preservation of comments. Thanks for your feedback

**Closed by wessberg** 2021-05-04 20:35 UTC

**Comment by thernstig** [comment] 2021-05-05 06:09
We do use Prettier, but unfortunately Prettier cannot account for self-made white spaces such as line breaks to delimit parts in the code. This renders the usage of this tool not possible for us unfortunately, but thanks anyway for a good tool.
